### PR TITLE
[swift 4.2] Updated code and dependencies for support swift 4.2 on iOS

### PR DESCRIPTION
**Pull request by surkis**

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks for putting this together!

**Comment by AKoulabukhov** [comment]
@greg-db is there a chance to have this PR merged in the near time?

**Comment by greg-db** [comment]
@AKoulabukhov I can't offer a timeline unfortunately. I'll bring this up with the team again though.

**Comment by greg-db** [comment]
The podspec and Cartfile have been updated for Alamofire 4.7 in the latest release of the SwiftyDropbox SDK.

**Pull request closed without merging**
