### PR TITLE
Add proper support for Swift Package Manager

### PR DESCRIPTION
**Pull request by bengottlieb**
- replaced DBChunkInputStream ObjC implementation with a Swift version
- cleaned up Package.swift
- fixed a problem extracting parameters from the auth URL

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks!

**Comment by vmanot** [comment]
Any update? It's frankly a bit concerning that this hasn't been done by the official team themselves yet.

**Comment by greg-db** [comment]
@vmanot No, I don't have an update on this yet.

**Comment by YufeiG** [comment]
Changes here were pulled into https://github.com/dropbox/SwiftyDropbox/pull/332
Thanks for your help!

**Pull request closed without merging**
