### PR TITLE
Added ability to specify request timeout. Closes #161

### LINKED ISSUE #161: Ability to specify request timeouts
I'm building an IOS app that will operate offline if dropbox is not available. SwiftyDropbox does a nice job of letting me know when there is no connection however if api.dropbox.com is not available it takes 60 seconds for the request to timeout (default).

I looked to see what I can do to override this behavior however with the manager:SessionManger being declared a constant I cannot override the SessionManager and reconfigure it.

**There should be a way to specify a default timeout when creating the DropBoxClient.**

### PR DESCRIPTION
**Pull request by tomkroening**
Added requestTimeout to constructors of DropBoxClient and DropBoxTransportClient so that when supplied it will be included in the SessionManager configuration.

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks for putting this together. We'll take a look.

**Comment by sshnip** [comment]
Hi.
Is it possible to resolve merge conflicts? Would be nice to have timeout control feature...

**Comment by sshnip** [comment]
@greg-db I understand. Thank you for your efforts anyway!

**Comment by greg-db** [comment]
Closing per [update](https://github.com/dropbox/SwiftyDropbox/issues/161#issuecomment-1875634118).

**Pull request closed without merging**
