### PR TITLE
Update syntax and dependencies to support swift 2.3

### PR DESCRIPTION
**Pull request by ianyh**

### CODE REVIEW

**Comment by cliftonlabrum** [comment]
Someone please merge and release this. iOS 10 launches in 2 days and I can't even build my app in Xcode 8 right now because SwiftyDropbox + Alamofire won't build in Swift 2.3. :)

**Comment by greg-db** [comment]
Thanks! We're working on it.

**Comment by winter7621** [comment]
What's the update on this? My stupid machine automatically updated Xcode so now I'm stuck

**Comment by scobbe** [comment]
Fixed by 5253602.

**Pull request closed without merging**
