### PR TITLE
Swift 5.0

### PR DESCRIPTION
**Pull request by StefaniOSApps**

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks for putting this together!

**Comment by StefaniOSApps** [comment]
Do you want to merge this? @greg-db

**Comment by greg-db** [comment]
@StefaniOSApps Thanks for checking in. The team will need to review and test this. I don't have a timeline for this right now, but we'll follow up here once we have an update on this.

**Comment by slizeray** [comment]
@greg-db Do you have any "update" for this trivial PR?

**Comment by greg-db** [comment]
@slizeray No, unfortunately I don't have any news on this yet.

**Comment by greg-db** [comment]
SwiftyDropbox has been updated to Swift 5 in the latest release.

**Pull request closed without merging**
