### PR TITLE
Update Alamofire dependency to latest release (4.7.0)

### LINKED ISSUE #204: Update Alamofire dependency to the latest release, v4.7.0
As long as Alamofire is used (and I agree with #200 that it shouldn't be), SwiftyDropbox should use the latest version.

### PR DESCRIPTION
**Pull request by gereons**
fixes #204

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks for submitting this!

**Comment by Vyazovoy** [comment]
Hi! Any chances that this highly urgent and useful PR will be merged? This Alamofire version mismatch blocks me.

**Comment by Vyazovoy** [comment]
Also it would be great to use just `~> 4.7` because according to semantic versioning it is safe

**Comment by gereons** [comment]
@Vyazovoy feel free to use my fork `pod 'SwiftyDropbox', :git => "https://github.com/gereons/SwiftyDropbox"` until this gets merged. '~> 4.7.0' does the right thing, it picks up every version up to but not including 4.8.

@greg-db it would really be nice if easy changes like this could get merged in a more timely fashion.

**Comment by greg-db** [comment]
Thanks for the feedback! I'll bring this up with the team.

**Comment by Vyazovoy** [comment]
@gereons I've already been using you fork, thank you. Yes, you are right that `~>4.7.0` will pick up to but not including 4.8 but picking 4.8 also safe as it will have only additional changes without any breaking changes. Only 5.x will have breaking changes according to semver.

**Comment by netizen01** [comment]
@greg-db Come one team. This one's been open for 10 months now. I've been using @gereons fork (thanks!) since then, but you really should get this merged in.

**Comment by greg-db** [comment]
@netizen01 Thanks for the note. I'll ask the team to see if we can get this prioritized.

**Comment by greg-db** [comment]
The podspec and Cartfile have been updated for Alamofire 4.7 in the latest release of the SwiftyDropbox SDK.

**Pull request closed without merging**
