### PR TITLE
Change min macOS version to 10.10

### PR DESCRIPTION
**Pull request by serejahh**
Hi
I want to use the lib on macOS 10.10, but min target was 10.11. It seems it works ok on 10.10 as well. Please, tell me if you know why it cannot support macOS 10.10
Thanks in advance

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks! I'll ask the team if this is something we can support.

**Comment by alek-prykhodko** [comment]
Hi, @greg-db !
Have you already asked the team?

**Comment by greg-db** [comment]
@alek-prykhodko Yes, I have asked the team to look at this. I can't promise a timeline for when they'll be able to do so though.

**Comment by serejahh** [comment]
Hey. Is any update here?

**Comment by greg-db** [comment]
@serejahh No, I don't have an update on this request.

**Comment by serejahh** [comment]
What about now? No updates?

**Comment by greg-db** [comment]
@serejahh No, I'm afraid I don't have any news on this request.

**Comment by YufeiG** [comment]
Hi, min for OSX is now 10.12 to support Alamofire 5

**Pull request closed without merging**
