### PR TITLE
Alamofire 4.3.0

### PR DESCRIPTION
**Pull request by ened**
Also updated the README.md with some basic notes.

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks! I'll have the team review this.

**Comment by InderKumarRathore** [comment]
When will be this merged ?

**Comment by greg-db** [comment]
I don't have a timeline right now unfortunately.

**Comment by akshaynhegde** [comment]
@greg-db Would really appreciate it if you can get it reviewed and merged.

**Comment by scobbe** [comment]
@akshaynhegde: Sorry for the delay. I will get to this within the next 48 hours – thanks for your patience!

**Comment by scobbe** [comment]
Thanks for making these changes! Sorry for the ridiculously long delay here.

**Pull request merged**
