### PR TITLE
Update for Xcode 10 and Swift 4.2

### PR DESCRIPTION
**Pull request by SofteqDG**
Here are the list of changes:
1. Alamofire dependency was updated to version 4.7.0 for both Carthage & CocoaPods
2. Format of the Package.swift was updated to PackageDescription V4
3. Project settings for framework and tests were updated for Xcode 10.0
4. Source code was updated for Swift 4.2

### CODE REVIEW

**Comment by greg-db** [comment]
Thanks for putting this together!

**Comment by SofteqDG** [comment]
@greg-db, 
Could you please merge this? I think a lot of users are waiting for Swift 4.2 support :)
PS: This PR also fixes #237 #231 #207 #204 issues and closes the #233 #232 #205 PR's

**Comment by CarlJNash** [comment]
Hey guys,
It would be really good to get this reviewed and merged.
Xcode 10/Swift 4.2 was released 2 months ago now the library really needs updated to support this.

**Comment by crspybits** [comment]
It could be useful to get a line in the podspec too:

      s.swift_version = '4.2'

to help with future Swift version incompatibilities.

**Comment by greg-db** [comment]
@crspybits Thanks for the note!

**Comment by SofteqDG** [comment]
@crspybits, 
Nice catch! Thanks!

@greg-db,
I've updated pull request. Please take a look on it.

**Comment by greg-db** [comment]
@SofteqDG Thanks! This is still pending for review with the team; I'll check in with them.

**Comment by AKoulabukhov** [comment]
@svpranay Hi, is there any news about review?
Thanks.

**Comment by SofteqDG** [comment]
Hi @joshzana,
Rebase is finished. I can not say that i've fully tested this PR. Currently i'm using it in my project to login, fetch file list and download separate files. Everything works fine for me. Unfortunately i can't perform tests as described in readme because i'm a bit busy on my work.

**Comment by joshzana** [comment]
OK I updated the stone generator code in https://github.com/dropbox/stone/pull/124 and bumped the stone submodule here.

After that, I ran through the tests on iOS and macOS, and everything seems to be great.

Landing this now on master, and will create a 5.0.0 in the next day or so.

**Comment by SofteqDG** [comment]
@joshzana,
Awesome! Thanks a lot!

**Pull request merged**
